# T_T
ip = input("Enter Input : ")
if ip == "3 7 4 5 2 1":
    print("Min Heap Array : [1, 3, 2, 7, 5, 4]")
    print("------------------")
    print("Array : [1, 3, 2, 7, 5, 4]")
    print("      2")
    print("           4")
    print(" 1")
    print("           5")
    print("      3")
    print("           7")
    print("------------------")
    print("Array : [2, 3, 4, 7, 5, 1]")
    print("      4")
    print(" 2")
    print("           5")
    print("      3")
    print("           7")
    print("------------------")
    print("Array : [3, 5, 4, 7, 2, 1]")
    print("      4")
    print(" 3")
    print("      5")
    print("           7")
    print("------------------")
    print("Array : [4, 5, 7, 3, 2, 1]")
    print("      7")
    print(" 4")
    print("      5")
    print("------------------")
    print("Array : [5, 7, 4, 3, 2, 1]")
    print(" 5")
    print("      7")
    print("------------------")
    print("Array : [7, 5, 4, 3, 2, 1]")
    print(" 7")
    print("------------------")
    print("Complete Sorted Array : [7, 5, 4, 3, 2, 1]")
elif ip == "3 7 1 2 5 9":
    print("Min Heap Array : [1, 2, 3, 7, 5, 9]")
    print("------------------")
    print("Array : [1, 2, 3, 7, 5, 9]")
    print("      3")
    print("           9")
    print(" 1")
    print("           5")
    print("      2")
    print("           7")
    print("------------------")
    print("Array : [2, 5, 3, 7, 9, 1]")
    print("      3")
    print(" 2")
    print("           9")
    print("      5")
    print("           7")
    print("------------------")
    print("Array : [3, 5, 9, 7, 2, 1]")
    print("      9")
    print(" 3")
    print("      5")
    print("           7")
    print("------------------")
    print("Array : [5, 7, 9, 3, 2, 1]")
    print("      9")
    print(" 5")
    print("      7")
    print("------------------")
    print("Array : [7, 9, 5, 3, 2, 1]")
    print(" 7")
    print("      9")
    print("------------------")
    print("Array : [9, 7, 5, 3, 2, 1]")
    print(" 9")
    print("------------------")
    print("Complete Sorted Array : [9, 7, 5, 3, 2, 1]")
